# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

chappelle = Headliner.create(name: "Dave Chappelle", length: 3, political: 3, controversial: 4, dirty: 4, opinionated: 5 )
louis = Headliner.create(name: "Louis CK", length: 2, political: 3, controversial: 5, dirty: 5, opinionated: 3 )
burr = Headliner.create(name: "Bill Burr", length: 5, political: 4, controversial: 4, dirty: 4, opinionated: 5 )
hedberg = Headliner.create(name: "Mitch Hedberg", length: 1, political: 3, controversial: 2, dirty: 2, opinionated: 1)
schumer = Headliner.create(name: "Amy Schumer", length: 2, political: 1, controversial: 3, dirty: 5, opinionated: 4)
ellen = Headliner.create(name: "Ellen Degeneres", length: 2, political: 2, controversial: 1, dirty: 1, opinionated: 2)
seinfeld = Headliner.create(name: "Jerry Seinfeld", length: 1, political: 2, controversial: 1, dirty: 1, opinionated: 5)
gaffigan = Headliner.create(name: "Jim Gaffigan", length: 1, political: 3, controversial: 1, dirty: 1, opinionated: 4)
williams = Headliner.create(name: "Robin Williams", length: 4, political: 3, controversial: 2, dirty: 4, opinionated: 2)
tosh = Headliner.create(name: "Daniel Tosh", length: 2, political: 4, controversial: 4, dirty: 4, opinionated: 4)
hicks = Headliner.create(name: "Bill Hicks", length: 4, political: 4, controversial: 5, dirty: 5, opinionated: 5)
carlin = Headliner.create(name: "George Carlin", length: 3, political: 2, controversial: 4, dirty: 3, opinionated: 5)


Opener.create(name: "Neal Brennan", length: 2, political: 2, controversial: 3, dirty: 2, opinionated: 3, headliner: chappelle) 
Opener.create(name: "Michelle Wolf", length: 3, political: 2, controversial: 5, dirty: 3, opinionated: 4, headliner: chappelle) 
Opener.create(name: "Michael Che", length: 2, political: 1, controversial: 3, dirty: 2, opinionated: 4, headliner: chappelle)
Opener.create(name: "Roy Wood Jr.", length: 3, political: 1, controversial: 3, dirty: 2, opinionated: 4, headliner: chappelle)
Opener.create(name: "Marc Maron", length: 4, political: 2, controversial: 3, dirty: 3, opinionated: 5, headliner: louis)
Opener.create(name: "Patton Oswalt", length: 4, political: 1, controversial: 4, dirty: 3, opinionated: 5, headliner: louis)
Opener.create(name: "Kyle Kinane", length: 2, political: 2, controversial: 3, dirty: 3, opinionated: 4, headliner: louis)
Opener.create(name: "Ari Shaffir", length: 3, political: 3, controversial: 4, dirty: 4, opinionated: 4, headliner: louis)
Opener.create(name: "Chelsea Peretti", length: 2, political: 2, controversial: 3, dirty: 3, opinionated: 4, headliner: louis)
Opener.create(name: "Joe Derosa", length: 2, political: 3, controversial: 5, dirty: 4, opinionated: 5, headliner: burr)
Opener.create(name: "Ronny Chieng", length: 3, political: 2, controversial: 3, dirty: 2, opinionated: 5, headliner: burr)
Opener.create(name: "Tom Segura", length: 3, political: 3, controversial: 4, dirty: 4, opinionated: 4, headliner: burr)
Opener.create(name: "Patrice O'neal", length: 3, political: 3, controversial: 5, dirty: 5, opinionated: 4, headliner: burr)
Opener.create(name: "Lewis Black", length: 1, political: 2, controversial: 4, dirty: 3, opinionated: 5, headliner: burr)
Opener.create(name: "Demeteri Martin", length: 1, political: 3, controversial: 2, dirty: 1, opinionated: 1, headliner: hedberg)
Opener.create(name: "Zach Galafianakis", length: 1, political: 3, controversial: 3, dirty: 2, opinionated: 1, headliner: hedberg)
Opener.create(name: "Steven Wright", length: 1, political: 3, controversial: 1, dirty: 1, opinionated: 1, headliner: hedberg)
Opener.create(name: "Nick Thune", length: 2, political: 2, controversial: 2, dirty: 2, , opinionated: 2, headliner: hedberg)
Opener.create(name: "Iliza Schlesinger", length: 3, political: 2, controversial: 3, dirty: 3, opinionated: 4, headliner: schumer)
Opener.create(name: "Nikki Glaser", length: 2, political: 2, controversial: 3, dirty: 4, opinionated: 3, headliner: schumer)
Opener.create(name: "Ali Wong", length: 2, political: 2, controversial: 3, dirty: 3, , opinionated: 3, headliner: schumer)
Opener.create(name: "Chris D'Elia", length: 3, political: 3, controversial: 3, dirty: 3, opinionated: 5, headliner: schumer)
Opener.create(name: "Natasha Leggero", length: 2, political: 2, controversial: 3, dirty: 4, opinionated: 4, headliner: schumer)
Opener.create(name: "Nate Bargatze", length: 3, political: 3, controversial: 1, dirty: 1, opinionated: 2, headliner: ellen)
Opener.create(name: "Brian Regan", length: 2, political: 2, controversial: 1, dirty: 1, opinionated: 4, headliner: ellen)
Opener.create(name: "Paula Poundstone", length: 2, political: 1, controversial: 2, dirty: 1,opinionated: 3, headliner: ellen)
Opener.create(name: "Dwayne Perkins", length: 2, political: 2, controversial: 2, dirty: 1, opinionated: 3, headliner: ellen)
Opener.create(name: "Maria Bamford", length: 2, political: 3, controversial: 3, dirty: 2, opinionated: 1, headliner: williams)
Opener.create(name: "Connor O'Malley", length: 3, political: 2, controversial: 3, dirty: 3, opinionated: 3, headliner: williams)
Opener.create(name: "Eric Andre", length: 1, political: 3, controversial: 3, dirty: 4, opinionated: 3, headliner: williams)
Opener.create(name: "Mike Birbiglia", length: 3, political: 2, controversial: 2, dirty: 2, opinionated: 1, headliner: williams)
Opener.create(name: "Doug Stanhope", length: 5, political: 2, controversial: 5, dirty: 5, opinionated: 5, headliner: hicks)
Opener.create(name: "Tim Dillon", length: 4, political: 4, controversial: 5, dirty: 4, opinionated: 5, headliner: hicks)
Opener.create(name: "Colin Quinn", length: 3, political: 4, controversial: 3, dirty: 4, opinionated: 5, headliner: hicks)
Opener.create(name: "Dave Attell", length: 2, political: 3, controversial: 4, dirty: 4, opinionated: 3, headliner: hicks)
Opener.create(name: "Nick Mullen", length: 3, political: 2, controversial: 5, dirty: 5, opinionated: 5, headliner: tosh)
Opener.create(name: "Anthony Jesilnik", length: 1, political: 3, controversial: 5, dirty: 5, opinionated: 4, headliner: tosh)
Opener.create(name: "Jimmy Carr", length: 1, political: 3, controversial: 5, dirty: 3, opinionated: 3, headliner: tosh)
Opener.create(name: "TJ Miller", length: 2, political: 3, controversial: 3, dirty: 3, opinionated: 3, headliner: tosh)
Opener.create(name: "Hannibal Buress", length: 2, political: 2, controversial: 1, dirty: 2, opinionated: 4, headliner: seinfeld)
Opener.create(name: "Mark Normand", length: 1, political: 3, controversial: 3, dirty: 3, opinionated: 4, headliner: seinfeld)
Opener.create(name: "Aziz Ansari", length: 3, political: 2, controversial: 1, dirty: 2, opinionated: 4, headliner: seinfeld)
Opener.create(name: "Gary Gulman", length: 3, political: 2, controversial: 1, dirty: 1, opinionated: 3, headliner: seinfeld)
Opener.create(name: "Dan Mintz", length: 1, political: 2, controversial: 5, dirty: 4, opinionated: 3, headliner: seinfeld)
Opener.create(name: "John Mulaney", length: 3, political: 2, controversial: 1, dirty: 2, opinionated: 4, headliner: seinfeld)
Opener.create(name: "Kurt Brounohler", length: 2, political: 3, controversial: 3, dirty: 2, opinionated: 4, headliner: gaffigan)
Opener.create(name: "Paul F. Tompkins", length: 4, political: 2, controversial: 2, dirty: 2, opinionated: 4, headliner: gaffigan)
Opener.create(name: "Dana Carvey", length: 1, political: 2, controversial: 1, dirty: 1, opinionated: 3, headliner: gaffigan)
Opener.create(name: "Pete Holmes", length: 2, political: 2, controversial: 2, dirty: 1, opinionated: 3, headliner: gaffigan)
Opener.create(name: "Frank Caliendo", length: 2, political: 3, controversial: 1, dirty: 1, opinionated: 3, headliner: gaffigan)
Opener.create(name: "Jim Jeffries", length: 3, political: 3, controversial: 4, dirty: 4, opinionated: 5, headliner: carlin)
Opener.create(name: "Lenny Bruce", length: 4, political: 2, controversial: 5, dirty: 4, opinionated: 5, headliner: carlin)
Opener.create(name: "Stewart Lee", length: 3, political: 2, controversial: 4, dirty: 3, opinionated: 5, headliner: carlin)
Opener.create(name: "Shane Mauss", length: 2, political: 2, controversial: 3, dirty: 3, opinionated: 4, headliner: carlin)






